# Generated by Django 4.1 on 2023-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_post_delete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to="Uploaded Files/%y/%m/%d/"),
                ),
                ("fileDatetime", models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
