# Generated by Django 4.1 on 2023-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_images_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                (
                    "head_image",
                    models.ImageField(blank=True, upload_to="mainApp/images/%Y/%m/%d"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="images",
        ),
    ]
